spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/t2_game_service?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: release
    #active: dev

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml



